http:
  routers:
    teste-router:
      rule: Host(`teste.jerasoft.com.br`) || Host(`lucas.jerasoft.com.br`)
      service: teste-service
      entryPoints:
      - websecure
      tls:
        certResolver: acmeresolver
  services:
    teste-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.1:80
